### ISSUE TITLE
Parse _junit_01.xml_ for test suite run results on <=v1.25

### ISSUE THREAD

**Issue by BobyMCbobs** [cncf-infra/verify-conformance#40]
e2e.log is useful for human output; due to a recent change in the test runner, https://github.com/kubernetes/kubernetes/commit/3e560e8341c47a5b9d383ef7af5a476bddacea5c, an expected JSON structure was missing.
_junit_01.xml_ contains enough information regarding the tests to solely rely on it.

~~- [ ] replace aggregating tests, completed and failed, based off on _junit_01.xml_ instead of e2e.log~~
- [ ] for v1.25 and above, use junit for determining test completions

supersedes #39

**Comment by BobyMCbobs** [comment]
it will be required for submissions below v1.25 to still rely on the _e2e.log_, since those submissions will contain the required information where it's not available in the _junit_01.xml_

**Comment by Riaankl** [comment]
@BobyMCbobs  We might want to set up the logic to use only the junit_01.xml no just for v1.26 but all releases > v1.25, which mean 1.26 and 1.27 - 1.xx would also work.
