### ISSUE TITLE
Document CNCF-CI bot resources for migration to K8s Infra resources

### ISSUE THREAD

**Issue by Riaankl** [cncf-infra/verify-conformance#78]
## Create a verbose .org file with links to map the CNCF-CI bot resources:
- List all the resouces with links
- Where is the images and docker files?
- How are the docker files built?
- Where is the Prow config file located?
- On which Kubernetes cluster is the prow job running?
- Which repos are connected to the CNCF-CI bot
- How is monitor switching done?
- Which repos must be migrated to Kubernetes .org
- In which CNCF AWS Account is used for the CNCF-CI bot??
- What else is in the account? 
- Should the account be migrated to Kubernetes AWS or should a new account be created?

**Comment by hh** [comment]
Focus on what we currently have and where it's located (and credentials to reach / reconfigure them).
We'll do another ticket (set of tickets) for each of the steps in the migration itself.

**Comment by BobyMCbobs** [comment]
added a resources document to describe the conformance infrastructure: https://github.com/cncf-infra/verify-conformance/pull/79

Things I'm not sure about

> On which Kubernetes cluster is the prow job running?

there aren't any Prow jobs which are running that are related to conformance that I'm aware of.

> How is monitor switching done?

what does this mean?

**Comment by BobyMCbobs** [comment]
this was completed. The doc is located here
https://github.com/cncf-infra/verify-conformance/blob/main/docs/resources.md
