### ISSUE TITLE
conformance.yaml not being updated

### ISSUE THREAD

**Issue by BobyMCbobs** [cncf-infra/verify-conformance#89]
It appears that the expected _./kodata/conformance-testdata_ isn't being populating.

https://github.com/cncf-infra/verify-conformance/actions/runs/5873165680/job/15926008062#step:4:2

**Comment by BobyMCbobs** [comment]
this condition
https://github.com/cncf-infra/verify-conformance/actions/runs/5873165680/workflow#L28
must be removed

**Comment by BobyMCbobs** [comment]
this should be tested again with removal of the `kodata/conformance-testdata/v1.28/conformance.yaml` file and retriggering the job.

**Comment by Riaankl** [comment]
@BobyMCbobs I created a [revert PR](https://github.com/cncf-infra/verify-conformance/pull/96) to undo the work of the bot, then we should allow the bot to recreate it through it's automated trigger.

**Comment by Riaankl** [comment]
@BobyMCbobs I think that is good to close? WDYT?

**Comment by BobyMCbobs** [comment]
Yeah, it's working good enough now!
