### ISSUE TITLE
Limit K8s Conformance submissions to only require the files needed for conformance verification

### ISSUE THREAD

**Issue by Riaankl** [cncf-infra/verify-conformance#98]
This is part of an attempt to keep the volume of data to be cloned by users submitting conformance results as low as possible.

Tasks:
- [x] Update the CNCF-CI bot to only allow the 4 requiered files to be submitted to the CNCF/K8s-Conformance repo.
- [ ] Add an error message that state "The submission contain more the the required files. Please only submit PRODUCT.yaml, README.md, e2e.log, junit_01.xml.
- [ ] Update the documentation to match the change. docs: content of the PR, and requirements.
  - [ ] [content of the PR](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#contents-of-the-pr)
  - [ ]   [requirements](https://github.com/cncf/k8s-conformance/blob/master/instructions.md#requirements)

**Comment by BobyMCbobs** [comment]
@Riaankl, I added two PRs to add a new check in and docs
- https://github.com/cncf-infra/verify-conformance/pull/99
- https://github.com/cncf/k8s-conformance/pull/2823
